# Generated by Django 4.2.15 on 2024-10-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crawl",
            options={"ordering": ["-started"]},
        ),
    ]
